language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry composer dumpautoload

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

before_install:
  - pip install --user codecov

after_success:
  - codecov